schedules:
  - tasks: '*'
    interval:
      minutes: 30

variables: secrets.yml

templates:
 
  addToTransmission:
    transmission:
      host: '{? trans.host ?}'
      port: 9091
      username: '{? trans.user ?}'
      password: '{? trans.password ?}'

  global:
    notify:
      entries:
        title: '{{title}}'  
        message: '{{title}} added to Transmission successfully.'
        via:
          - email:
              from: '{? email.from ?}'
              to: '{? email.to ?}'
              smtp_host: smtp.gmail.com
              smtp_port: 587
              smtp_username: '{? email.user ?}'
              smtp_password: '{? email.password ?}'
              smtp_tls: yes
              html: yes 
tasks:
  search-anime:
    rss: '{? url.anime ?}'
    series:
      settings:
        shows:
          identified_by: sequence
          tracking: no
      shows:
        - Black Clover
        - Dr. Stone
        - Yakusoku no Neverland
        - Shingeki no Kyojin
        - One Punch Man
        - DanMachi
        - Kimetsu no Yaiba
        - Boku no Hero Academia
        - Tensei Shitara Slime Datta Ken
        - Fruits Basket
        - Shokugeki no Soma
        - Bokutachi wa Benkyou ga Dekinai
        - Psycho-Pass
        - Assassin's Pride
        - Babylon
        - Choujin Koukousei-tachi
        - Ahiru no Sora
        - Chuubyou Gekihatsu Boy
    template: addToTransmission
  search-series:
    rss: '{? url.tv ?}'
    series:
      settings:
        shows:
          quality: 720p+ hdtv
          identified_by: ep
          tracking: no
      shows:
        - Marvels Agents of S H I E L D
        - The Mandalorian
    template: addToTransmission
