schedules:
  - tasks: '*'
    interval:
      minutes: 30

variables: secrets.yml

templates:
 
  addToTransmission:
    transmission:
      host: '{? trans.host ?}'
      port: 9091
      username: '{? trans.user ?}'
      password: '{? trans.password ?}'

  global:
    notify:
      entries:
        title: '{{title}}'  
        message: '{{title}} added to Transmission successfully.'
        via:
          - email:
              from: '{? email.from ?}'
              to: '{? email.to ?}'
              smtp_host: smtp.gmail.com
              smtp_port: 587
              smtp_username: '{? email.user ?}'
              smtp_password: '{? email.password ?}'
              smtp_tls: yes
              html: yes 
tasks:
  search-anime:
    rss: '{? url.anime ?}'
    series:
      settings:
        shows:
          identified_by: sequence
          tracking: no
      shows:
        - Black Clover
        - Golden Kamuy
        - Goblin Slayer
        - Seishun Buta Yarou
        - Zombie Land Saga
        - Gaikotsu Shoten’in Honda-san
        - Irozuku Sekai no Ashita kara
        - Banana Fish
        - Shingeki no Kyojin
        - Tensei Shitara Slime Datta Ken
    template: addToTransmission
  search-series:
    rss: '{? url.tv ?}'
    series:
      settings:
        shows:
          quality: 720p+ hdtv
          identified_by: ep
          tracking: no
      shows:
        - Marvels Agents of S H I E L D
        - Alex Inc
    template: addToTransmission
